name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "8.1", "8.0", "7.4" ]
  pull_request:
    branches: [ "8.1", "8.0", "7.4" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: "andriykryvenko/bitrix-app:${{ github.ref.name }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
        run: docker build -t ${{ env.IMAGE_NAME }} --no-cache --force-rm .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the Docker image
        uses: actions/checkout@v3
        run: docker run -d --name bitrix-app ${{ env.IMAGE_NAME }}

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: andriykryvenko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: true